const CONFIG = {
  API_CHAT_ENDPOINT: "/api/chat",
  API_AUTH_ME_ENDPOINT: "/api/auth/me",
  API_LOGIN_ENDPOINT: "/api/auth/login",
  API_SIGNUP_ENDPOINT: "/api/auth/signup",
  API_LOGOUT_ENDPOINT: "/api/auth/logout",
  API_CONVERSATIONS_ENDPOINT: "/api/conversations",
  API_PROFILES_ENDPOINT: "/api/profiles",
  API_ONBOARDING_ENDPOINT: "/api/onboarding",
  API_ROADMAPS_ENDPOINT: "/api/roadmaps",
  API_TASKS_ENDPOINT: "/api/tasks",
  API_DASHBOARD_ENDPOINT: "/api/dashboard",
  API_NOTIFICATIONS_ENDPOINT: "/api/notifications",
  MAX_INPUT_LENGTH: 4000,
  MAX_HISTORY_TURNS: 20,
  SUBJECTS: {
    general: "General Mentor",
    math: "Mathematics",
    science: "Science",
    coding: "Programming",
    writing: "Writing & Essays",
    history: "History",
  },
};
